Repository AlfredSimpson/IT490-LongSoup, pull requests merged in 2023-12, with the labels that each got.

#72 Revised Scripts - missing exchange info + wrong variables
  DB/DMZ_Testing/ProceduralRequestTest.py
  DB/DMZ_Testing/StoreDMZtoDB.py
  DMZ/DMZWorker.py
  DMZ/procedural_data_script.py
Labels: enhancement, Mandatory Implementation, Linchpin

#73 Justin 2 fa testing
  DB/2FA/LongAuthMessage.py
  DB/2FA/TESTDBWorker.py
  DB/2FA/verify.ejs
  DB/DBWorker.py
  DB/LongAuthMessage.py
  WebServer/package.json
  WebServer/views/authenticate.ejs
  WebServer/webserver/server.js
  WebServer/webserver/server_old.js
Labels: enhancement, Mandatory Implementation, Linchpin

#79 Messages repair: Midterm Deliverable (Past Due)
  .gitignore
  DB/DBWorker.py
  DB/DBmbWorker.py
  DB/Profiles/profile.json
  DB/Profiles/user_playlists.json
  Utilities/systemd-services/constantclipboard.service
  Utilities/systemd-services/keephoppingCGS.service
  WebServer/_webserver.log
  WebServer/public/js/messageboard.js
  WebServer/views/account/messageboard.ejs
  WebServer/views/testinglogin.ejs
  WebServer/webserver/routes/accountsRouter.js
  WebServer/webserver/routes/api.js
  WebServer/webserver/server.js
Labels: enhancement, Mandatory Implementation

#80 David systemd
  DMZ/GetRecommendations.py
  Utilities/systemd-services/dmz-apiscripts.service
  Utilities/systemd-services/dmz-apiscripts.sh
  Utilities/systemd-services/dmz-worker.service
  Utilities/systemd-services/dmz-worker.sh
  Utilities/systemd-services/storedmz.service
  Utilities/systemd-services/storedmz.sh
Labels: Mandatory Implementation

#82 SSL now works
  .gitignore
  WebServer/_Unknown-Origins.log
  WebServer/_Web.log
  WebServer/_webserver.log
  WebServer/_webserver_rmq.log
  WebServer/webserver/routes/accountsRouter.js
  WebServer/webserver/routes/api.js
  WebServer/webserver/server.js
Labels: Mandatory Implementation, Linchpin

#83 Web upgrade
  WebServer/_webserver.log
  WebServer/package-lock.json
  WebServer/package.json
  WebServer/public/js/accounts.js
  WebServer/public/js/handler.js
  WebServer/public/js/longajax.js
  WebServer/views/account/profile.ejs
  WebServer/views/partials/head.ejs
  WebServer/views/success.ejs
  WebServer/webserver/routes/accountsRouter.js
  WebServer/webserver/routes/api.js
  WebServer/webserver/server.js
Labels: enhancement, Mandatory Implementation, Linchpin

#84 Profile visibility
  DB/DBProfileWorker.py
  DB/DBSpotWorker.py
  READMEs/Issues.md
  WebServer/_webserver.log
  WebServer/views/account/profile.ejs
  WebServer/views/partials/loggedheader.ejs
  WebServer/webserver/routes/accountsRouter.js
  WebServer/webserver/routes/api.js
Labels: Mandatory Implementation

#85 Updated DBSpotWorker
  DB/DBSpotWorker.py
Labels: Mandatory Implementation

#88 Profile visibility
  DB/DBProfileWorker.py
  DB/DBSpotWorker.py
  DB/DBWorker.py
  WebServer/_webserver.log
  WebServer/package-lock.json
  WebServer/package.json
  WebServer/public/js/handler.js
  WebServer/public/js/profilehandler.js
  WebServer/views/account/profile.ejs
  WebServer/views/account/userprofile.ejs
  WebServer/views/forum.ejs
  WebServer/views/partials/loggedheader.ejs
  WebServer/webserver/routes/accountsRouter.js
  WebServer/webserver/routes/api.js
  WebServer/webserver/server.js
Labels: enhancement
